bool signInInterface(string username, string password);
void adminInterface();
void employeeInterface();
string adminChoice();
string employeeChoice();
bool adminFunctionChoosers(string option, string usernameOfUser);
bool employeeFunctionChoosers(string option, string usernameOfEmployee);
void initialSignUp();
bool addUserInterface(string usernameOfUser);
bool userAuthenticate(string name);
void addUser(string username, string password, string role);
void viewUsersInfo();
void viewSpecificUser(int index);
void updateUserInterface(string username);
void updateUserInfo(string username);
bool deleteUserInterface(string username);
void deleteUser(string username);
void addUsersToFile();
void loadUsersFromFile();
void addManufacturingOrder();                    
bool orderPriceVerification(string price);       
bool orderQuantityVerification(string quantity); 
void viewManufacturingOrders();
void updateManufacturingOrders();
void deleteManufacturingOrderInterface();  
void deleteManufacturingOrders(int index); 
bool isFlavorInTheSystem(string flavor);
void addManufacturingOrdersToFile();
void readManufacturingOrdersFromFile();
void addIngredients();
void viewIngredientsOrdered();
void updateIngredientsOrdered();
void deleteIngredientsOrdered();
bool isIngredientInTheTable(string ingredient);
void addIngredientsOrdersToFile();
void readIngredientsOrdersFromFile();
void addIngredientsToTheTable();
void viewIngredientsInTheTable();
void deleteIngredientsFromTheTable();
void addIngredientsToFile();
void readIngredientsFromFile();
void viewCheetosFlavors();
void deleteFlavorsFromSystem();
void addFlavorsToFile();
void readFlavorsFromFile();
void viewRecommendedIngredients();
void viewExcessIngredients();
void uploadIngredientRequest(string usernameOfEmployee);
void viewIngredientRequest(string usernameOfEmployee);
void editRequestForIngredients(string usernameOfUser);
void deleteRequestForIngredients(string usernameOfEmployee);
void addIngredientsRequestToFile();
void readIngredientsRequestFromFile();
void addIngredientsInShortage();
void addIngredientsInShortageToFile();
void readIngredientsInShortageFromFile();
void addIngredientsInExcess();
void addIngredientsInExcessToFile();
void readIngredientsInExcessFromFile();
void viewFeedbackFromEmployee();
void detailFeedbackView(int serialNumber);
void addFeedbackToFile();
void readFeedbackFromFile();
void addRequests(string employeeUsername);
void addIngredientChangeRequestToFile();
void readingIngredientChangeRequestFromFile();
bool stringNumberValidate(string number);
string parse(string line, int field);
string getRole(string username);
void invalidUserPrompt();
void header();
void subHeader(string nameMenu);
int adminCount();
int userIndex(string username);
int numberOfRequestsByAUser(string usernameOfEmployee);
int indexOfRequestBySerialNumber(string serialNumberToUpdate, string usernameOfUser);


